### ISSUE TITLE
Create a single script to run all the scripts periodically

### ISSUE THREAD

**Issue by shreyas44** [shreyas44/bedav#15]
Create a single script (shell or python) to run scripts for all the cities periodically.
The script has to execute the files for each region (currently `bangalore.py`, `pune.py` and `andhra.py`) periodically (every hour).

*Note: It should be an infinite loop*

**Comment by sudiptog81** [comment]
Working on this.

**Comment by shreyas44** [comment]
Alright! Assigned it to you.
