### ISSUE TITLE
Search Engine Optimization

### ISSUE THREAD

**Issue by shreyas44** [shreyas44/bedav#26]
**Is your feature request related to a problem? Please describe.**
Currently the description in Search Engines is `bedavFind the hospital you need. Home. About. Last Updated on 12 Oct, 12:01 PM. Available. 35,110. Occupied. 37,807. Total. 72,917. District. Available.`.

**Describe the solution you'd like**
Change the description to something better which describes what the website shows and offers. Add any other additional SEOs.

**Comment by fibonacci-spirals** [comment]
Hi @shreyas44 I would like to take this up!

**Comment by shreyas44** [comment]
@fibonacci-spirals sure! I've assigned it to you!

**Comment by shreyas44** [comment]
@fibonacci-spirals any updates?

**Comment by fibonacci-spirals** [comment]
Hi, @shreyas44 I have generated the meta descriptions for HTML as well as specific properties for Google, Facebook and Twitter. I am having trouble running the website on my local machine with docker. From the logs I can see that it compiles, but when I ping the server I get a Connection Refused error. I believe this might be related to running docker on MacOS Catalina and I am working to resolve it. I would appreciate any information you might have to resolve this (or if I could just run the webpack server without docker). Thanks!

**Comment by shreyas44** [comment]
Hi @fibonacci-spirals, that sounds great! I'm running Docker on macOS Catalina as well and it seems to run fine. Could you ping me on Discord, so we can figure this out?

**Comment by shreyas44** [comment]
@fibonacci-spirals I pushed an update to master which fixes the issue. Can you pull the latest commit from master and see if it works?
