### ISSUE TITLE
Update sources in About page

### ISSUE THREAD

**Issue by shreyas44** [shreyas44/bedav#28]
**Is your feature request related to a problem? Please describe.**
Currently, the sources in the about page mention the sources of data only for Pune and Bangalore. However, more cities were added ever since that page was created.

**Describe the solution you'd like**
Update the about page to include sources as mentioned in [SOURCES](https://github.com/shreyas44/bedav/blob/master/SOURCES.md)

The content for the about page can be found at https://github.com/shreyas44/bedav/blob/7413e9f32e27fd5c5960f911060d2e8a9a5b08a5/website/src/components/about/AboutPage.js#L37

**Additional context**
About page at present:
![Screen Shot 2020-10-23 at 3 40 24 AM](https://user-images.githubusercontent.com/46835608/96935345-7ea6f480-14e1-11eb-9614-7c194061ca97.png)
Sources for the other regions available on the website have to be added.

**Comment by jeremylgrice** [comment]
I would be up for helping on this one if that's okay?

**Comment by shreyas44** [comment]
@jeremylgrice Sure! Let me know if you need any help :)
